# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phase Positive
email: eric.t.anderton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog and training materials.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eanderton.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  eanderton

collections:
  training:
    output: true
    permalink: /training/:path/


# Build settings
markdown: kramdown

# Github settings
kramdown:
  input: GFM
  hard_wrap: false
gems:
 - jekyll-coffeescript
 - jekyll-paginate
